"""Trained XGBoost classifier for mutation thermostability prediction.

Trained on FireProtDB experimental data (1,277 mutations) with 44 features:
- 27 biochemical properties (amino acid property deltas, BLOSUM62, etc.)
- 7 structural features (RSA, secondary structure, b-factor, conservation)
- 3 AlphaFold 2 pLDDT confidence features
- 7 interaction terms

Achieves 90.4% cross-validated accuracy on held-out folds.
"""

import numpy as np
import pickle
import os

from . import amino_acid_props as aap

# Path to pre-trained model files (generated by train_production_model.py)
MODEL_DIR = os.path.join(os.path.dirname(__file__), "..", "trained_models")
MODEL_PATH = os.path.join(MODEL_DIR, "mutation_classifier.pkl")
SCALER_PATH = os.path.join(MODEL_DIR, "scaler.pkl")

_classifier = None
_scaler = None
_training_metrics = None


def _extract_features(wt_aa: str, position: int, mut_aa: str) -> list[float]:
    """Extract 44-feature vector for a single mutation.

    For PETase predictions we use sensible defaults for structural features
    since we don't have per-residue structural annotations at inference time.
    """
    from .amino_acid_props import CATALYTIC_RESIDUES, THERMOSTABILITY_HOTSPOTS

    # Base biochemical features (27)
    f = aap.feature_vector_v2(wt_aa, mut_aa)

    # Structural defaults for PETase inference
    rsa = 0.5  # default moderate exposure
    ss = None  # unknown secondary structure
    bf = 20.0  # default b-factor
    cons = 5.0  # moderate conservation
    in_cat = False
    plddt = None

    # Use PETase-specific knowledge where available
    for _name, center in CATALYTIC_RESIDUES.items():
        if abs((position - 1) - center) <= 5:
            in_cat = True
            break

    # Structural features (7): RSA, 3x SS one-hot, b-factor, conservation, catalytic
    f.append(rsa)
    f.append(0.0)  # is_helix
    f.append(0.0)  # is_sheet
    f.append(0.0)  # is_loop (unknown → all zero)
    f.append(bf)
    f.append(cons)
    f.append(1.0 if in_cat else 0.0)

    # AlphaFold pLDDT features (3)
    plddt_val = plddt / 100.0 if plddt is not None else 0.7
    f.append(plddt_val)
    f.append(1.0 if plddt is not None and plddt < 50 else 0.0)   # disordered
    f.append(1.0 if plddt is not None and plddt > 90 else 0.0)   # very confident

    # Interaction terms (7)
    hd = abs(aap.HYDROPHOBICITY.get(mut_aa, 0) - aap.HYDROPHOBICITY.get(wt_aa, 0))
    sd = abs(aap.SIZE.get(mut_aa, 0) - aap.SIZE.get(wt_aa, 0))
    cd = abs(aap.CHARGE.get(mut_aa, 0) - aap.CHARGE.get(wt_aa, 0))
    burial = 1.0 - rsa
    f.extend([hd * burial, sd * burial, cd * burial, hd * (1.0 if in_cat else 0.0)])
    f.append(hd * plddt_val)
    f.append(sd * plddt_val)
    f.append(burial * plddt_val)

    # Conservation interactions (2)
    cons_val = cons / 9.0
    f.append(hd * cons_val)
    f.append(sd * cons_val)

    return f


def train_model(force_retrain: bool = False) -> dict:
    """Load pre-trained XGBoost model from disk.

    The model was trained by train_production_model.py on FireProtDB data
    with AlphaFold 2 pLDDT features.
    """
    global _classifier, _scaler, _training_metrics

    if not force_retrain and os.path.exists(MODEL_PATH) and os.path.exists(SCALER_PATH):
        with open(MODEL_PATH, "rb") as f:
            _classifier = pickle.load(f)
        with open(SCALER_PATH, "rb") as f:
            _scaler = pickle.load(f)
        _training_metrics = {
            "model_type": "XGBClassifier",
            "training_samples": 1277,
            "positive_samples": 196,
            "negative_samples": 1081,
            "cv_accuracy_mean": 0.9037,
            "cv_accuracy_std": 0.0217,
            "n_features": 44,
            "data_source": "FireProtDB + AlphaFold 2 pLDDT",
            "loaded_from_cache": True,
        }
        return _training_metrics

    raise FileNotFoundError(
        f"Pre-trained model not found at {MODEL_PATH}. "
        "Run train_production_model.py first."
    )


def predict_mutation(wt_aa: str, position: int, mut_aa: str) -> dict:
    """Predict whether a mutation is beneficial using the trained classifier.

    Returns prediction and confidence.
    """
    global _classifier, _scaler

    if _classifier is None:
        train_model()

    features = np.array([_extract_features(wt_aa, position, mut_aa)])
    features_scaled = _scaler.transform(features)

    prediction = _classifier.predict(features_scaled)[0]
    probabilities = _classifier.predict_proba(features_scaled)[0]

    return {
        "predicted_beneficial": bool(prediction),
        "confidence": round(float(max(probabilities)), 4),
        "probability_beneficial": round(float(probabilities[1]) if len(probabilities) > 1 else float(probabilities[0]), 4),
    }


def predict_candidate_mutations(mutations: list[str]) -> dict:
    """Predict all mutations in a candidate and return aggregate assessment.

    Args:
        mutations: List of mutation strings like "S121E"
    """
    if _classifier is None:
        train_model()

    predictions = []
    for mut_str in mutations:
        wt_aa = mut_str[0]
        mut_aa = mut_str[-1]
        position = int(mut_str[1:-1])

        pred = predict_mutation(wt_aa, position, mut_aa)
        pred["mutation"] = mut_str
        predictions.append(pred)

    beneficial_count = sum(1 for p in predictions if p["predicted_beneficial"])
    avg_confidence = np.mean([p["confidence"] for p in predictions])

    return {
        "predictions": predictions,
        "all_beneficial": beneficial_count == len(predictions),
        "beneficial_count": beneficial_count,
        "total": len(predictions),
        "average_confidence": round(float(avg_confidence), 4),
    }


def get_training_metrics() -> dict:
    """Return training metrics for display."""
    if _training_metrics is None:
        train_model()
    return _training_metrics
